import { randomUUID } from "node:crypto";

import { CronExpressionParser } from "cron-parser";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";

import type {
  MeshAgent,
  MeshMessageHistoryEntry,
  ReminderRow,
} from "./mesh-types";

export const MESH_TOOL_NAMES = [
  "reply",
  "fetch_messages",
  "list_agents",
  "create_reminder",
  "list_reminders",
  "cancel_reminder",
] as const;

export type MeshToolName = (typeof MESH_TOOL_NAMES)[number];

export interface MeshToolsHub {
  send(opts: {
    to: string;
    from: string;
    content: string;
    reply_to: string | null;
  }): Promise<unknown>;
  listAgents(): Promise<MeshAgent[]>;
  fetchMessages(opts: {
    agentId: string;
    limit?: number;
  }): Promise<MeshMessageHistoryEntry[]>;
  scheduleReminder(opts: {
    id: string;
    type: "once" | "cron";
    scheduleSpec: string;
    payload: string;
    nextFireAt: string;
    context?: string;
    idempotencyKey?: string;
  }): Promise<{ ok: boolean; id: string; type: string; next_fire_at: string }>;
  cancelReminder(id: string): Promise<{ changes: number }>;
  listReminders(opts: { status?: string; limit?: number }): Promise<ReminderRow[]>;
}

export interface MeshToolDefinition {
  name: MeshToolName;
  description: string;
  inputSchema: Record<string, unknown>;
}

export interface MeshToolResult extends CallToolResult {
  content: [{ type: "text"; text: string }];
}

export interface MeshToolDispatcherOptions {
  hub: MeshToolsHub;
  laneIdentity: string;
}

function toStringArg(args: Record<string, unknown>, name: string): string {
  const value = args[name];
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`${name} is required`);
  }
  return value;
}

function normalizeLimit(value: unknown, fallback: number, max: number): number {
  const parsed =
    typeof value === "number"
      ? value
      : typeof value === "string"
        ? Number.parseInt(value, 10)
        : fallback;
  if (!Number.isInteger(parsed) || parsed <= 0) return fallback;
  return Math.min(parsed, max);
}

function flattenContent(raw: string): string {
  return raw.replace(/[\r\n]+/g, " ").trim();
}

type ReminderType = "once" | "cron";

function toRecordArg(args: Record<string, unknown>, name: string): Record<string, unknown> {
  const value = args[name];
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${name} must be an object`);
  }
  return value as Record<string, unknown>;
}

function optionalStringArg(
  args: Record<string, unknown>,
  name: string,
): string | undefined {
  const value = args[name];
  if (value === undefined) return undefined;
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`${name} must be a non-empty string when provided`);
  }
  return value;
}

function sqliteUtc(date: Date): string {
  if (Number.isNaN(date.getTime())) throw new Error("invalid date");
  return date.toISOString().replace("T", " ").slice(0, 19);
}

function generatedReminderId(args: Record<string, unknown>): string {
  if (Object.hasOwn(args, "id")) {
    const supplied = args.id;
    if (typeof supplied !== "string" || supplied.trim() === "") {
      throw new Error("id must not be blank; reminder ids are generated by the adapter");
    }
    throw new Error("id is generated by the adapter and must not be supplied");
  }
  return `rem_${randomUUID().replace(/-/g, "")}`;
}

function createOnceSchedule(schedule: Record<string, unknown>): {
  scheduleSpec: string;
  nextFireAt: string;
} {
  const at = toStringArg(schedule, "at");
  if (!/(?:Z|[+-]\d{2}:\d{2})$/i.test(at)) {
    throw new Error("once schedule.at must include a UTC offset (for example 2026-07-13T12:00:00Z)");
  }
  const date = new Date(at);
  if (Number.isNaN(date.getTime())) throw new Error("once schedule.at is not a valid ISO-8601 time");
  if (date.getTime() <= Date.now()) throw new Error("once schedule.at must be in the future");
  return {
    scheduleSpec: JSON.stringify({ at }),
    nextFireAt: sqliteUtc(date),
  };
}

function createCronSchedule(schedule: Record<string, unknown>): {
  scheduleSpec: string;
  nextFireAt: string;
} {
  const cron = toStringArg(schedule, "cron");
  const tz = optionalStringArg(schedule, "tz") ?? "UTC";
  try {
    const next = CronExpressionParser.parse(cron, { tz }).next().toDate();
    return {
      scheduleSpec: JSON.stringify({ cron, tz }),
      nextFireAt: sqliteUtc(next),
    };
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new Error(`invalid cron schedule: ${detail}`);
  }
}

function reminderSchedule(
  type: ReminderType,
  schedule: Record<string, unknown>,
): { scheduleSpec: string; nextFireAt: string } {
  return type === "once" ? createOnceSchedule(schedule) : createCronSchedule(schedule);
}

export const MESH_TOOL_DEFINITIONS: readonly MeshToolDefinition[] = [
  {
    name: "reply",
    description:
      "Reply to an Agent-Mesh sender. Pass chat_id from the inbound channel message; it is the destination mesh identity.",
    inputSchema: {
      type: "object",
      properties: {
        chat_id: { type: "string", description: "Destination mesh identity, usually the inbound chat_id." },
        text: { type: "string", description: "Message text to send through Agent-Mesh." },
        reply_to: { type: "string", description: "Optional mesh message id to thread under. Use inbound message_id when needed." },
      },
      required: ["chat_id", "text"],
    },
  },
  {
    name: "fetch_messages",
    description: "Fetch recent Agent-Mesh messages between this Codex lane and another mesh identity.",
    inputSchema: {
      type: "object",
      properties: {
        agent_id: { type: "string", description: "Peer mesh identity to fetch conversation history for." },
        limit: { type: "number", description: "Max messages to return, default 20, max 200." },
      },
      required: ["agent_id"],
    },
  },
  {
    name: "list_agents",
    description: "List registered Agent-Mesh identities and online state.",
    inputSchema: { type: "object", properties: {} },
  },
  {
    name: "create_reminder",
    description: "Create a once or cron self-reminder for this Codex lane. The adapter generates the reminder id.",
    inputSchema: {
      type: "object",
      properties: {
        type: { type: "string", enum: ["once", "cron"], description: "Reminder schedule type." },
        schedule: { type: "object", description: 'For once: {"at":"2026-07-13T12:00:00Z"}. For cron: {"cron":"0 18 * * 1-5","tz":"Asia/Seoul"}.' },
        payload: { type: "string", description: "Plain-text reminder message delivered to this lane." },
        context: { type: "string", description: "Optional plain-text context appended by the poller." },
        idempotency_key: { type: "string", description: "Optional active-reminder deduplication key." },
      },
      required: ["type", "schedule", "payload"],
    },
  },
  {
    name: "list_reminders",
    description: "List reminders owned by this Codex lane.",
    inputSchema: {
      type: "object",
      properties: {
        status: { type: "string", enum: ["active", "paused", "fired", "cancelled", "exhausted", "dead", "all"], description: "Status filter; defaults to active." },
        limit: { type: "number", description: "Maximum rows to return; defaults to 50, max 200." },
      },
    },
  },
  {
    name: "cancel_reminder",
    description: "Cancel an active reminder owned by this Codex lane.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Reminder id returned by create_reminder or list_reminders." },
      },
      required: ["id"],
    },
  },
];

export async function dispatchMeshTool(
  options: MeshToolDispatcherOptions,
  name: string,
  args: Record<string, unknown>,
): Promise<MeshToolResult> {
  try {
    switch (name) {
      case "reply": {
        const to = toStringArg(args, "chat_id");
        const text = toStringArg(args, "text");
        const replyTo = typeof args.reply_to === "string" && args.reply_to.trim() !== ""
          ? args.reply_to
          : null;
        const result = (await options.hub.send({
          to,
          from: options.laneIdentity,
          content: text,
          reply_to: replyTo,
        })) as { id?: string; status?: string };
        const sentId = result.id ? ` id=${result.id}` : "";
        const status = result.status ? ` status=${result.status}` : "";
        return { content: [{ type: "text", text: `sent${sentId}${status}` }] };
      }
      case "fetch_messages": {
        const agentId = toStringArg(args, "agent_id");
        const messages = await options.hub.fetchMessages({
          agentId,
          limit: normalizeLimit(args.limit, 20, 200),
        });
        const text = messages.length === 0
          ? "(no messages)"
          : messages.map((message) => {
            const content = flattenContent(message.content);
            return `[${message.ts}] ${message.from} -> ${message.to}: ${content} (id=${message.id} status=${message.status})`;
          }).join("\n");
        return { content: [{ type: "text", text }] };
      }
      case "list_agents": {
        const agents = await options.hub.listAgents();
        const text = agents.length === 0
          ? "(no agents)"
          : agents.map((agent) => {
            const state = agent.online ? "online" : "offline";
            const type = agent.type ? ` type=${agent.type}` : "";
            const lastSeen = agent.last_seen ? ` last_seen=${agent.last_seen}` : "";
            const desc = agent.description ? ` - ${flattenContent(agent.description)}` : "";
            return `${agent.id} (${state}${type}${lastSeen})${desc}`;
          }).join("\n");
        return { content: [{ type: "text", text }] };
      }
      case "create_reminder": {
        const type = toStringArg(args, "type");
        if (type !== "once" && type !== "cron") throw new Error("type must be once or cron");
        const id = generatedReminderId(args);
        const payload = toStringArg(args, "payload");
        const schedule = reminderSchedule(type, toRecordArg(args, "schedule"));
        const context = optionalStringArg(args, "context");
        const idempotencyKey = optionalStringArg(args, "idempotency_key");
        const result = await options.hub.scheduleReminder({
          id,
          type,
          scheduleSpec: schedule.scheduleSpec,
          payload,
          nextFireAt: schedule.nextFireAt,
          ...(context === undefined ? {} : { context }),
          ...(idempotencyKey === undefined ? {} : { idempotencyKey }),
        });
        if (!result.ok) throw new Error("reminder was not created (duplicate active idempotency key)");
        const rows = await options.hub.listReminders({ status: "all", limit: 200 });
        const inserted = rows.find((row) => row.id === result.id);
        if (!inserted) throw new Error("reminder was created but could not be read back from this lane");
        return {
          content: [{
            type: "text",
            text: JSON.stringify({ ...inserted, agent_id: options.laneIdentity, created_by: options.laneIdentity }),
          }],
        };
      }
      case "list_reminders": {
        const status = optionalStringArg(args, "status") ?? "active";
        const allowedStatuses = new Set(["active", "paused", "fired", "cancelled", "exhausted", "dead", "all"]);
        if (!allowedStatuses.has(status)) throw new Error("invalid reminder status");
        const rows = await options.hub.listReminders({
          status,
          limit: normalizeLimit(args.limit, 50, 200),
        });
        return { content: [{ type: "text", text: JSON.stringify({ lane: options.laneIdentity, rows }) }] };
      }
      case "cancel_reminder": {
        const id = toStringArg(args, "id");
        const result = await options.hub.cancelReminder(id);
        if (result.changes !== 1) throw new Error("reminder not found, not active, or not owned by this lane");
        return { content: [{ type: "text", text: JSON.stringify({ id, status: "cancelled", lane: options.laneIdentity }) }] };
      }
      default:
        return { content: [{ type: "text", text: `unknown tool: ${name}` }], isError: true };
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { content: [{ type: "text", text: `${name} failed: ${message}` }], isError: true };
  }
}
